### ISSUE TITLE
Add italic tag for introductions ufsm tags and  AT quotes in NT tag.

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#17]
Hello,
This is a proposal for enhancement. It would be very nice if u2o.py can automatically convert the tag \ip \is... and \qt (OT quotation in NT) with the italic tag in the output osis file. Because currently I need to add the \it \it* manually in the introduction, and it a big job!
Maybe adding this option to u2o can help us. And for me it's more readable when we can make difference between intro and Bible.

**Comment by DavidHaslam** [comment]
My view is that the proper place to implement rendering styles of such semantic elements is not at the conversion to OSIS but in the rendering of OSIS by the SWORD API or the JSword API.

As long as such features are not yet built in to the engines, for some front-end applications, they can be achieved by having an ancillary style sheet in the module path. Xiphos supports this already.

**Comment by LAfricain** [comment]
>My view is that the proper place to implement rendering styles of such semantic elements is not at the conversion to OSIS but in the rendering of OSIS by the SWORD API or the JSword API.

I understand your opinion, but till it is not implemented u2o.py may do it no? If no I will use my u2o.py fork to do this :)

>...achieved by having an ancillary style sheet in the module path.

Can you give me how to use this style sheet?

**Comment by adyeths** [comment]
This would be something that the rendering engine that is used to render the osis file should handle. That's why my script (and every other converter I've seen) puts introduction material inside a div marking it as such. _The use of presentational tags in osis is discouraged._

**Comment by alerque** [comment]
I agree this tool shouldn't mess with things outside the scope of proper structural OSIS markup. In fact rather than trying to change this project I would recommend approaching whatever project you use for display and fixing it on that end using the markup that is already there. That being said if you really need to hack this into your workflow for use in a tool that doesn't render OSIS well I suggest writing yourself a little tools to munge the XML output after it is generated — XSLT being the most likely candidate for that sort of work. Such a modification might get you my for internal use, but I would not encourage the distribution of such a modified document however as it will only encourage display tooling to put off adding the proper feature to their rendering.

**Comment by LAfricain** [comment]
Hello,
I understood everything you said, I accept that without difficulty. For me I was just seeing a bigger problem, I have to put a tag \ \it \it* in all the introductions, and in all the quotes of the AT in the NT. It's a heavy job, plus for every tag \it Bibledit-Desktop tells me it is deprecated, so for a control tags when there are more than 1000 it's quite complicated. So italicizing only in the osis file was for me a more user-friendly solution.
I do not know at all if we can report a bug on xiphos so that it can allow the display of introductions as well as citations in italics, nor how to create css files for that. I do not know anything about programming and all these things, and I would not be able to develop any tools. In the immediate future I forked u2o and I just added the necessary italic so that I do not need to do it in the usfm file anymore.

If you can give me hints for this italic display problem in xiphos I would be very grateful.

**Comment by LAfricain** [comment]
Thank you very much!

**Comment by alerque** [comment]
@LAfricain I've opened two issues on the Xiphos tracker. There are undoubtedly other UIs that could use the same attention, but since you mention that project for your own use (and I use it too) I figured we could start there. No promises  because I'm kind of swamped these days but that might even be something I could contribute to Xiphos. It wouldn't be a hard change, I just haven't hacked on it in a while and am not setup to do so at the moment.

**Comment by LAfricain** [comment]
@alerque OK Thanks. Two modules are affected, the linvb (not yet available) and the konnym, rename konvb (will be update with intros, and OT quotes, and notes).

**Comment by alerque** [comment]
@LAfricain Would you be able to send me one or both of those modules (over a private channel if need be) generated with the stock output from this version of `u2o` for testing?

**Comment by DavidHaslam** [comment]
When you are ready to submit KonVB module to CrossWire, remember to include the following line in konvb.conf
```
Obsoletes=KonNYM
```

Remember that module names are case sensitive.

**Comment by LAfricain** [comment]
@alerque For [konvb](https://gitlab.com/lafricain79/konvb) dand [linVB](https://gitlab.com/lafricain79/LinVB). For konvb wait fews days I'll generate te module, or generate it yourself if you prefer.
