### ISSUE TITLE
Support for USFM 3.0 

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#3]
**USFM 3.0** is on its way. See https://github.com/ubsicap/usfm

From your commit today, I see that you've _already_ begun to work on this.

This merely provides a reference point for anyone else that may be interested in your script.

If you look at the [issues](https://github.com/ubsicap/usfm/issues), you'll see that I have been adding quite a few myself.

Not yet had a response to these from [klassenjm](https://github.com/klassenjm).
I did actually meet him at a conference in Germany during 2012 and we are also friends on facebook.

David

**Comment by DavidHaslam** [comment]
Don't forget to add the new markers to your [utaglist.py](https://github.com/adyeths/u2o/blob/master/utaglist.py)

**Comment by adyeths** [comment]
This is essentially finished. So I'm going to close this issue.

**Comment by DavidHaslam** [comment]
I see that you've so far implemented the **milestone start and end** syntax _only_ for the **example** given in the [documentation](https://ubsicap.github.io/usfm/milestones/) `\qt-s` and `\qt-s` when in fact the syntax could be generalised for all potential markers where the text may span over several paragraphs.

Of course, **quoted text** is the most likely candidate for this application, but there's no intrinsic reason to not cater for other markers.

I should think that `\wj_...\wj*` would be the next most likely candidate, so at least `\wj-s\*` and `\wj-e\*` should be implemented too.

**Comment by adyeths** [comment]
qt-s was added because it was mentioned. There was no mention of this for the wj marker.

There are two conditions that if either of them are met I will implement this for the wj marker (or other markers).
1. there is a need for support for a milestone version of the marker.
2. the documentation for usfm is updated to indicate that the milestone version of the particular marker is valid.

This form of marker is more complicated to implement than most others. I really need to see something more concrete on it's need before I work on adding more tags using this milestone syntax. Adding support for more tags arbitrarily just doesn't make sense and doesn't seem like a wise use of my time.

**Comment by DavidHaslam** [comment]
Now also see [#55](https://github.com/ubsicap/usfm/issues/55) just added.

**Comment by DavidHaslam** [comment]
See now also issue [#55](https://github.com/ubsicap/usfm/issues/55) that I added for USFM.
