### ISSUE TITLE
Creating the [ABBR] section of the config file by scripting?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#32]
It should be relatively simple to make a script that can extract the `\toc# ` lines from a set of USFM files and use the data to generate the `[ABBR]` section of the config file for `orefs.py`

It should be a separate script, as the output will usually require some manual editing before it can be utilised.

The script should provide some suggestions for what to do when `\toc3 abbr` lines are absent.

They are not mandatory yet.

Take care for any abbreviations that include the period terminator such as `Gen.` rather than `Gen` that you may be more accustomed to seeing.

Some Bible translations have a mixture of abbreviations like that and others that are without a period because the bookname is short enough already, **Job** being the usual instance.

Then the cross-references need to be very carefully parsed.

**Comment by adyeths** [comment]
orefs can be modified to automatically create a conf file. This is something I had planned on anyway.

---

Some explanation on how orefs works…

Right now, when orefs automatically grabs the book names and abbreviations, it only adds what is present. The absence of toc3 would only mean one less abbreviation in the list for that book. (This would be true for automatic generation of the conf file as well.) The absence of both toc2 and toc3 would mean no abbreviations for the book and no ability to process cross references pointing to those books.

Before any parsing of cross references is attempted by orefs, the book names and abbreviations are processed and a tag is inserted in place of the abbreviation or book name. So something like this `Gen.` should work just fine if it were a book abbreviation. A period in a book abbreviation would not make any difference in processing the chapter and verse part of the reference where a period were used as one of the separators.

It should be noted that longer abbreviations should come before shorter abbreviations when editing the conf file. Otherwise, there will likely be problems processing the cross references.

**Comment by DavidHaslam** [comment]
> It should be noted that longer abbreviations should come before shorter abbreviations when editing the conf file. Otherwise, there will likely be problems processing the cross references.

Mention that in the README.

**Comment by adyeths** [comment]
Ability to automatically create a config file has been added to orefs.

**Comment by adyeths** [comment]
No need to add the need to put longer abbreviations before shorter abbreviations to the readme now. I added a sort to the abbreviations to do it automatically.
