### ISSUE TITLE
Strange terminal output from u2o.py

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#4]
When I used it today, the cygwin terminal gave a lot of output ending like this:

[cygwin.terminal.test.txt](https://github.com/adyeths/u2o/files/697231/cygwin.terminal.test.txt)

What's this all for? Why does this occur? 

This seems to be the output made by 
`    print(books['TEST'])`

Yet the code for this has:

```
    if 'TEST' in books.keys():
        print(books['TEST'])
```
But my USFM files do not have any books called TEST.
Just the 66 standard books each with correct **\id** tag.

NB. This output doesn't occur when I redirect command line results like this:

```
$ python aydeth/u2o.py -l pan -x -n punjabi3 Punjabi/*.usfm 1>u2o.log 2>u2o.err
or.log
```

FYI. the two log files are attached. _Extension .txt added to suit github._

[u2o.error.log.txt](https://github.com/adyeths/u2o/files/697223/u2o.error.log.txt)
[u2o.log.txt](https://github.com/adyeths/u2o/files/697224/u2o.log.txt)

The last line of the standard error log is also a mystery!

`UnicodeEncodeError: 'ascii' codec can't encode character u'\ufeff' in position 0: ordinal not in range(128)`

NB. The input files are all UTF-8 encoded (without BOM).

Something not quite right here?

**Comment by adyeths** [comment]
TEST is the default book id that is used when the book id cannot be determined by the script. That's why it would appear in the output when you have no book with that name.

As for WHY you got test output instead of the output you expected... it looks like there might be a byte order mark in one of the files that you tried to process. I will try to investigate this further. Do note that it will be problematic trying to track it down without access to the files that produced this error though.

**Comment by DavidHaslam** [comment]
I suppose I'll have to open each of the USFM

**Comment by DavidHaslam** [comment]
Yep! Found one already. 20_PROFBPa.usfm has a BOM.

**Comment by DavidHaslam** [comment]
I will process the USFM files again tomorrow.

There were no missing verses in the derived SWORD module, so the BOM having been detected was not a major problem for the resulting OSIS XML file.

**Comment by adyeths** [comment]
Since you had TEST output, the generated OSIS would have had some chapter/verse markers that used TEST in place of the actual book id that should have been used in the osisID, sID, and eID attributes.

I have adjusted u2o to allow for the possibility of a BOM being present in utf-8 encoded files. This issue should not be a problem any longer.

**Comment by DavidHaslam** [comment]
This morning (without a sync to get your updated script), I ran the conversion again (having removed the BOM last night).

This time there were no errors reported.

**Comment by DavidHaslam** [comment]
I can now also confirm that **PRO**verbs was omitted in the OSIS file that I made yesterday.

The new OSIS file I just made today includes it.

**Comment by DavidHaslam** [comment]
You wrote:

> I have adjusted u2o to allow for the possibility of a BOM being present in utf-8 encoded files. This issue should not be a problem any longer.

I hereby confirm that I have verified the solution. _Thanks_.
