### ISSUE TITLE
Chapter labels - command line option?

### ISSUE THREAD

**Issue by DavidHaslam** [adyeths/u2o#89]
Might it be desirable to have a **command line option** to cause chapter labels to become **titles** instead of **milestones**?

**Comment by adyeths** [comment]
No. As I have said repeatedly before, they are made milestones because the form of titles they are supposed to be set as according to the osis manual don't work properly in sword based software and cause problems when they are used. *This hasn't changed.* When sword based software is fixed to allow them to be properly displayed THEN I will change them back to using title tags. Not before.

**Comment by DavidHaslam** [comment]
OK - understood. 

We need to add an issue for the API in tracker.crosswire.org

Otherwise I don’t think anyone would pick it up for SWORD to be improved on this matter.
