### ISSUE TITLE
\cp tag in the middle of a regular chapter is not well convert

### ISSUE THREAD

**Issue by LAfricain** [adyeths/u2o#98]
Hello,
In some Catholic bible Esther has multiple \cp  tag in the middle of the the text of a regular \c tag. This tag is not well converted in the osis file.
The best way, probably is to ignore it and and the text of this tag in the previous verse. 
You can see the text in the attached file:
[17_Esther.zip](https://github.com/adyeths/u2o/files/4030037/17_Esther.zip)

**Comment by adyeths** [comment]
This doesn't look like a proper use of the \cp tag to me. Perhaps the \ca tag is more appropriate here.

**Comment by cmahte** [comment]
Based on the initial response from teh USFM 3.0 issues thread, the encoding for canonical introductions (considered verses before Chapter 1) by convention should be as you see below: 

Here's the initial response on the USFM issues thread: 
____

Hello Michael,

Thanks for pointing to this example. It appears to be a file containing "Esther Greek" (ESG) (portions of Esther found in the Greek translation of the Hebrew book of Esther). In my experience, these texts potentially ordered with chapter and verse markup in multiple different ways depending on the audience and church tradition the text is being published for, and how the text is published with or separate from the other parts of Esther. It has always been somewhat difficult to understand how the portions fit together, for me.

As USFM did emerge and grew out of some of the practices developed in the Paratext application, there was a need for markup which could identify the chapters and verses to actually display in a published text, even though Paratext expected a sequential order of chapter and verse markers. Different projects have atempted to describe the structure of ESG within this Paratext constraint using \cp and \vp. \ca and \va are normally used for showing multiple (an alternate) versififcation schemes.

You referered to a canonical introduction. I think I understand why you have described the text this way. In an English text example (Good News), the current project markup is as follows

\c 1
\cp A
\s Mordecai's Strange Dream
\p
\v 1-3 Mordecai, a Jew who belonged to the tribe of Benjamin, was taken into exile, 
along with King Jehoiachin of Judah...
...
\p
\v 17 But Haman son of Hammedatha, a Bougaean who was respected by the king, 
tried to cause trouble for Mordecai and his people the Jews, because Mordecai had 
been responsible for the death of the two eunuchs.
\cp 1
\s Queen Vashti Defies King Xerxes
\p
\v 18-19 \vp 1-2\vp* These things happened in the time of King Xerxes, who ruled 
127 provinces, all the way from India to Ethiopia,b from his royal throne in Susa, 
Persia's capital city.
\v 20 \vp 3\vp* In the third year of his reign, the king gave a banquet for all his 
advisers
...
The \cp (as a Paragraph type) appears within a sequential chapter section on its own (like \cp 1) -- or immediately after a \c (like \cp A).

As I mentioned, the pratice of marking up ESG is somewhat varied, and challenging. Does this alternative example help shed light on what others do and have done with this?

**Comment by adyeths** [comment]
I have altered how \cp and \vp tags are handled. They should now be converted to osis milestone markers. I can think of no other way to properly convert them to osis and still be able to handle this particular situation.

**Comment by LAfricain** [comment]
It's not working:
Ex:
```
<verse eID="Esth.10.2"/> <verse sID="Esth.10.3" osisID="Esth.10.3" n="3"/>Porque o judeu Mardoqueu era o primeiro, depois do rei Assuero; era considerado grande entre os judeus e amado pela multidão dos seus irmãos. Procurou o bem do seu povo e preocupou-se com a felicidade de toda a sua raça. \cp F</p><!-- s2 --><title>Interpretação do sonho de Mardoqueu</title><p><milestone type="x-usfm-va" n="1"/> E Mardoqueu disse: «De Deus veio tudo isto. <milestone type="x-usfm-va" n="2"/> Lembro-me de um sonho que tive a este respeito e nada foi omitido: <milestone type="x-usfm-va" n="3"/> foi a pequena fonte que se converteu num rio, e foi a luz e o sol e a abundância de água. O rio é Ester a quem o rei tomou por esposa e que se tornou rainha. <milestone type="x-usfm-va" n="4"/> Os dois dragões sou eu e Haman. <milestone type="x-usfm-va" n="5"/>
```

**Comment by adyeths** [comment]
Ok, it'll probably be a few weeks before I have time to spend on trying to fix this issue.

**Comment by LAfricain** [comment]
Ok no problem, thank you for your help.

**Comment by adyeths** [comment]
This is fixed now.
